#!/bin/bash
# This file was auto-generated by generate_loader
# It sources all .sh scripts in its own directory.

# Guard to prevent sourcing multiple times
if [[ -n "$LOADER_GIT_SHADOW_26AFBDF5_LOADED" ]]; then
 
